name: Go

on: [push, pull_request]

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        go: [1.13, 1.14, 1.15]

    runs-on: ${{matrix.os}}
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^${{matrix.go}}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get -v -t -d ./...        

    - name: Test
      run: go test -v .
